proj_data_entry/menej_class_sistem_cerdas/data_entry/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('data_entry/', views.set_data_entry,name='set_data_entry'),
    path('pengguna/',views.set_pengguna,name='set_pengguna'),
    path('pengguna/view/<id>',views.view_pengguna,name='view_pengguna'),
    path('api/pengguna/<int:user_id>/',views.get_pengguna_detail_api,name='get_pengguna_detail_api'),
    path('content/',views.set_content,name='set_content'),
    path('pengguna/listpenggunabystate',views.search_pengguna_by_state,name='search_pengguna_by_state'),
]

proj_data_entry/menej_class_sistem_cerdas/menej_class_sistem_cerdas/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(( 'data_entry.urls' , 'data_entry' ), namespace = 'data_entry' )),
]

proj_data_entry/menej_class_sistem_cerdas/data_entry/models.py
from django.db import models
from django import forms 
from datetime import date

# Create your models here.
class Pengguna (models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=100)
    address_1 = models.TextField()
    address_2  = models.TextField(null=True, blank = True)
    city = models.CharField(max_length=20, help_text='Enter your city')
    state= models.TextField()
    zip_code= models.CharField(max_length = 7)
    tanggal_join = models.DateField(auto_now = True)

    def __str__(self):
        return f'{self.email}'

class Content(models.Model):
    author =models.ForeignKey(Pengguna, on_delete=models.CASCADE)
    date_created = models.DateField(auto_now=True)
    artikel = models.TextField()
    set_view = models.BooleanField(default=False)

proj_data_entry/menej_class_sistem_cerdas/data_entry/forms.py
from django import forms
from .models import Pengguna,Content

STATES = (
    ('', 'Choose...'),
    ('DKI','Daerah Khusus Ibu Kota'),
    ('DIY','Daerah Istimewa Yogyakarta'),
    ('JaBar','Jawa Barat')
)
STATUS = (
    ('', 'Choose...'),
    ('S','Selesai'),
    ('B','Berlangsung'),
    ('G','Gagal')
)

class SearchPengguna(forms.Form):
    state = forms.ChoiceField(choices=STATES)

class AddressForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Email'}))
    password = forms.CharField(widget=forms.PasswordInput())
    address_1 = forms.CharField(
        label='Address',
        widget=forms.TextInput(attrs={'placeholder': '1234 Main St'})
    )
    address_2 = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Apartment, studio, or floor'})
    )
    city = forms.CharField()
    state = forms.ChoiceField(choices=STATES)
    zip_code = forms.CharField(label='Zip')
    check_me_out = forms.BooleanField(required=False)

class PenggunaForm(forms.ModelForm):
    state = forms.ChoiceField(choices=STATES)

    class Meta:
        model = Pengguna
        exclude = ['tanggal_join',]

class ContentForm(forms.ModelForm):

    class Meta:
        model = Content
        exclude = ['date_created']

proj_data_entry/menej_class_sistem_cerdas/data_entry/views.py
from django.shortcuts import render
from .forms import AddressForm, PenggunaForm, ContentForm, SearchPengguna
from .models import Pengguna,Content
from django.http import JsonResponse

# Create your views here.
def set_data_entry(request):
    form = AddressForm()
    context = {
        'form':form,
    }
    return render(request, 'data_entry/input_data_1.html',context)

def set_pengguna(request):
    list_pengguna = Pengguna.objects.all()
    context = None
    form = PenggunaForm(None)
    if request.method =="POST":
        form = PenggunaForm(request.POST)
        if form.is_valid():
            form.save()
            list_pengguna = Pengguna.objects.all()
            context = {
                'form':form,
                'list_pengguna':list_pengguna,
            }
            return render(request, 'data_entry/input_data_1.html',context)
    else:
        list_pengguna = Pengguna.objects.all()
        context = {
            'form':form,
            'list_pengguna':list_pengguna,
        }
        return render(request, 'data_entry/input_data_1.html',context)

def view_pengguna(request, id):
    try:
        pengguna = Pengguna.objects.get(pk=id)
        return render(request,'data_entry/pengguna_detail.html',{'user_id':pengguna.id})
    except Pengguna.DoesNotExist:
        return JsonResponse({'error': 'user not found'},status=404)

def get_pengguna_detail_api(requst, user_id):
    try:
        pengguna = Pengguna.objects.get(pk=user_id)
        data = {
            'email':pengguna.email,
            'address_1':pengguna.address_1,
            'address_2':pengguna.address_2,
            'city':pengguna.city,
            'state':pengguna.city,
            'zip_code':pengguna.zip_code,
            'tanggal_join':pengguna.tanggal_join.strftime('%Y-%m-%d') #format date as string
        }
        return JsonResponse(data)
    except Pengguna.DoesNotExist:
        return JsonResponse({'error':'User not found'},status=404)
    
def set_content(request):
    list_content = Content.objects.all()
    form = ContentForm(None)
    if request.method == 'POST':
        form = ContentForm(request.POST)
        if form.is_valid():
            form.save()
            list_content = Content.objects.all()
            context = {
                'form':form,
                'list_content':list_content,
            }
            return render(request, 'data_entry/content.html',context)
    else:
        context = {
            'form':form,
            'list_content':list_content,
        }
        return render(request, 'data_entry/content.html',context)
    
def search_pengguna_by_state(request):
    pesan = None
    tampil = None
    form = None
    listpengguna = None
    status = None
    if request.method == 'POST':
        form = SearchPengguna(request.POST)
        if form.is_valid():
            state = form.cleaned_data['state']
            listpengguna = Pengguna.objects.filter(state=state)
            if not listpengguna.exists():
                pesan = 'Data Pengguna Tidak Ditemukan'
                status = True
            else :
                tampil = True
    else:
        form = SearchPengguna()
    
    context = {
        'form': form,
        'tampil': tampil,
        'pesan': pesan,
        'tatus': status,
        'listpengguna': listpengguna,
    }
    return render(request, "data_entry/list_pengguna.html", context=context)

proj_data_entry/menej_class_sistem_cerdas/data_entry/templates/data_entry/MeaningfulPage.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Menu dan Tabel</title>
    <link rel="stylesheet" href="HomeStyle.css">
</head>
<body>
    <div id="container">
        <div id="sidebar">
            <button>Home</button>
            <button>Meaningful Objectives</button>
            <button>Intelligence Experience</button>
            <button>Intelligence Implementation</button>
            <button>Intelligence Dev & RealizationIS</button>
            <button>Setting</button>
            <button>USER_ID | Logout</button>
        </div>
        <p>USER_ID</p>
        <div id="content">
            <h2>Home</h2>
            <h4>Meaningful Objectives</h4>
            <div id="table-container">
                <table>
                    <tr>
                        <th>
                            <input type="text" placeholder="Search">
                            <button id="button">Search</button>
                        </th>
                    </tr>
                </table>
                <table>
                    <tr id="table-header">
                        <th>Organization Objective</th>
                        <th>Leading Indicator</th>
                        <th>User OutComes</th>
                        <th>Model Properties</th>
                        <th>Action</th>
                    </tr>
                    <tr>
                        <td>xxxxxxxxxxxxx</td>
                        <td>xxxxxxxxxxxxx</td>
                        <td>xxxxxxxxxxxxx</td>
                        <td>xxxxxxxxxxxxx</td>
                        <td>
                            <button id="button">Update</button>
                            <button id="button red">Delete</button>
                        </td>
                    </tr>
                </table>
            </div>
            <h2>Meaningful Objectives</h2>
            <div id="table-container">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group mb-0">
                    {{ form.organization_objective | as_crispy_field }}
                    {{ form.leading_indicator| as_crispy_field }}
                    {{ form.user_outcomes|as_crispy_field }}
                    {{ form.model_properties|as_crispy_field }}
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.tanggal_mulai|as_crispy_field }}
                      </div>
                      <div class="form-group col-md-6 mb-0">
                        {{ form.tanggal_selesai|as_crispy_field }}
                      </div>
                    </div>
                    <div class="form-group col-md-4 mb-0">
                    {{ form.status_penyelesaian| as_crispy_field }}
                    </div>
                    <button type="submit">Create</button>
                  </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

proj_data_entry/menej_class_sistem_cerdas/data_entry/templates/data_entry/content.html
{% extends 'base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit">Create</button>
  </form>
{% endblock %}

proj_data_entry/menej_class_sistem_cerdas/data_entry/templates/data_entry/input_data.html
{% extends 'base.html' %}


{% block content %}
  <form method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit">Sign in</button>
  </form>
{% endblock %}

proj_data_entry/menej_class_sistem_cerdas/data_entry/templates/data_entry/input_data_1.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} # pastikan sama persis
{% block content %}
<form method="post">
  {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6 mb-0">
    {{ form.email|as_crispy_field }}
    </div>
    <div class="form-group col-md-6 mb-0">
    {{ form.password|as_crispy_field }}
    </div>
    </div>
    {{ form.address_1|as_crispy_field }}
    {{ form.address_2|as_crispy_field }}
    <div class="form-row">
    <div class="form-group col-md-6 mb-0">
    {{ form.city|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
    {{ form.state| as_crispy_field }}
    </div>
    <div class="form-group col-md-2 mb-0">
    {{ form.zip_code|as_crispy_field }}
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>
  
  <div class="alert alert-warning" role="alert">
    Daftar Pengguna
  </div>
<table class="table table-bordered" id="data_entry_tbl">
  <thead>
      <tr >
          <th scope="col">Email</th>
          <th scope="col">Alamat 1</th>
          <th scope="col">Kota</th>
          <th scope="col">Profinsi</th>
          <th scope="col">Aksi</th>
      </tr>
  </thead>
  <tbody>


      {% for pengguna in list_pengguna %}
      <tr class = "record">
          <td><label >{{pengguna.email}}</label></td>
          <td><label >{{penggguna.addriss_1}}</label></td>
          <td><label >{{pengguna.city}}</label></td>
          <td><label >{{pengguna.state}}</label></td>
         
          <td>
               <form method="post" action="#">
                   {% csrf_token %}
                   <a href="{% url 'data_entry:view_pengguna' pengguna.id %}" class="btn btn-outline-success">View</a>
                   <a href="" class="btn btn-outline-success">Edit</a>
                   
              </form>
           </td>


      </tr>
      {% endfor %}
  </tbody>
</table> 
{% endblock %}

proj_data_entry/menej_class_sistem_cerdas/data_entry/templates/data_entry/list_pengguna.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="alert alert-warning" role="alert">
    Cari Data Pengguna
</div>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Cari</button>
</form>
{% if tampil %}
  <div class="alert alert-warning" role="alert">
    Daftar Pengguna
  </div>
  <table class="table table-bordered" id="data_entry_tbl">
    <thead>
      <tr>
          <th scope="col">Email</th>
          <th scope="col">Alamat 1</th>
          <th scope="col">Kota</th>
          <th scope="col">Provinsi</th>
          <th scope="col">Aksi</th>
      </tr>
    </thead>
    <tbody>
      {% for pengguna in listpengguna %}
      <tr class="record">
          <td><label>{{ pengguna.email }}</label></td>
          <td><label>{{ pengguna.address_1 }}</label></td>
          <td><label>{{ pengguna.city }}</label></td>
          <td><label>{{ pengguna.state }}</label></td>
          <td>
               <form method="post" action="#">
                   {% csrf_token %}
                   <a href="{% url 'data_entry:view_pengguna' pengguna.id %}" class="btn btn-outline-success">View</a>
                   <a href="" class="btn btn-outline-success">Edit</a>
              </form>
           </td>
      </tr>
      {% endfor %}
    </tbody>
  </table> 
{% endif %}
{% if status %}
<div class="alert alert-warning" role="alert">
    {{ pesan }}
</div>
{% endif %}
{% endblock %}

proj_data_entry/menej_class_sistem_cerdas/data_entry/templates/data_entry/pengguna_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block content %}

<h1> User Details</h1>
<div id="user_details">
  
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
      var userId = {{user_id}};

      fetch('/api/pengguna/' + userId + '/')
        .then(response => response.json())
        .then(data => {
            var userDetailsDiv = document.getElementById('user_details');
            var tableHtml = `
                  <table class="table">
                    <tbody>
                      <tr>
                        <th scope="row">Email</th>
                        <td>${data.email}</td>
                      </tr>
                      <tr>
                        <th scope="row">Address 1</th>
                        <td>${data.address1}</td>                            
                      </tr>
                      <tr>
                        <th scope="row">Address 2</th>
                        <td>${data.address2}</td>
                      </tr>
                      <tr>
                        <th scope="row">City</th>
                        <td>${data.city}</td>                            
                      </tr>
                      <tr>
                        <th scope="row">State</th>
                        <td>${data.state}</td>
                      </tr>
                      <tr>
                        <th scope="row">Zip</th>
                        <td>${data.zip}</td>                            
                      </tr>
                      <tr>
                        <th scope="row">Tanggal Join</th>
                        <td>${data.tanggal_join}</td>                            
                      </tr>
                    </tbody> 
                  </table>`;
            userDetailsDiv.innerHTML = tableHtml;
        })
        .catch(error => console.error('Error fetching user details', error));
    });
</script>
{% endblock %}

proj_data_entry/menej_class_sistem_cerdas/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">

    {% block content %}
    {% endblock %}
  </div>
</body>

</html>